name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download playit.gg Agent
      run: Invoke-WebRequest https://playit.gg/downloads/playit-win-64.exe -OutFile playit.exe

    - name: Move playit executable
      run: Move-Item -Path playit.exe -Destination .\playit\playit.exe
      shell: powershell
      continue-on-error: true

    - name: Authenticate playit.gg
      run: .\playit\playit.exe --secret_key ${{ secrets.PLAYIT_SECRET_KEY }}
      env:
        PLAYIT_SECRET_KEY: ${{ secrets.PLAYIT_SECRET_KEY }}

    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0

    - name: Enable Remote Desktop Firewall Rule
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Configure RDP Security
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: Set Local User Password
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Create Tunnel with playit.gg
      run: Start-Process -FilePath ".\playit\playit.exe" -ArgumentList "run" -NoNewWindow
