name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Download playit.gg client
      run: |
        # Thêm User-Agent và headers để tránh bị chặn
        $headers = @{
          'User-Agent' = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
          'Accept' = 'application/octet-stream'
        }
        try {
          Invoke-WebRequest -Uri "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.4/playit.exe" -OutFile "playit.exe" -Headers $headers -UseBasicParsing
          # Kiểm tra file đã tải về
          if (Test-Path "playit.exe") {
            $fileInfo = Get-Item "playit.exe"
            Write-Host "Downloaded file size: $($fileInfo.Length) bytes"
            if ($fileInfo.Length -lt 1MB) {
              Write-Host "File size suspicious, checking content..."
              Get-Content "playit.exe" -Head 5
            }
          }
        } catch {
          Write-Host "Download failed with error: $_"
          Write-Host "Trying alternative download method..."
          # Phương pháp thay thế
          curl -L -o playit.exe "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.4/playit.exe"
        }
        
    - name: Enable Remote Desktop (RDP)
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        
    - name: Create user TranAnhKhoa
      run: |
        net user TranAnhKhoa "AnhKhoa123@" /add
        net localgroup administrators TranAnhKhoa /add
        
    - name: Login to playit.gg
      run: |
        # Kiểm tra file playit.exe trước khi sử dụng
        if (Test-Path "playit.exe") {
          echo $Env:PLAYIT_SECRET | Out-File -Encoding ASCII secret.txt
          .\playit.exe login < secret.txt
        } else {
          Write-Host "playit.exe not found!"
          exit 1
        }
      env:
        PLAYIT_SECRET: ${{ secrets.PLAYIT_SECRET }}
        
    - name: Start Tunnel (TCP 3389)
      run: |
        if (Test-Path "playit.exe") {
          .\playit.exe serve
        } else {
          Write-Host "playit.exe not found!"
          exit 1
        }
