name: KL

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download playit.gg client
      run: |
        Invoke-WebRequest "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.4/playit.exe" -OutFile "playit.exe"

    - name: Enable Remote Desktop (RDP)
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Create user TranAnhKhoa
      run: |
        net user TranAnhKhoa "AnhKhoa123@" /add
        net localgroup administrators TranAnhKhoa /add

    - name: Login to playit.gg
      run: |
        echo $Env:PLAYIT_SECRET | Out-File -Encoding ASCII secret.txt
        .\playit.exe login < secret.txt
      env:
        PLAYIT_SECRET: ${{ secrets.PLAYIT_SECRET }}

    - name: Start Tunnel (TCP 3389)
      run: .\playit.exe serve
